import type { SimulatorConfig } from './schema';

export const config: SimulatorConfig = {
  meta: {
    product: "Kote's",
    brand: "Kote's",
    tagline: 'everyday goods, brightly done',
  },
  defaults: {
    seed: 20260627,
    now: '2026-06-27T09:00:00.000Z',
    locale: 'en-US',
    currency: 'USD',
    timeZone: 'UTC',
  },

  profiles: [
    {
      id: 'prof-demo',
      email: 'demo@kotes.test',
      password: 'demo1234',
      displayName: 'Sam Demo',
      behaviors: { role: 'member', locale: 'en-US' },
      seed: { orders: 4, addresses: 1 },
    },
    {
      id: 'prof-ren',
      email: 'ren@kotes.test',
      password: 'demo1234',
      displayName: 'Ren Okafor',
      behaviors: { role: 'member', locale: 'en-US' },
      seed: { orders: 3, addresses: 1 },
    },
    {
      id: 'prof-ays',
      email: 'ays@kotes.test',
      password: 'demo1234',
      displayName: 'Ays Bergström',
      behaviors: { role: 'member', locale: 'en-US', slowNetwork: true },
      seed: { orders: 42, addresses: 3 },
    },
    {
      id: 'prof-lena',
      email: 'lena@kotes.test',
      password: 'demo1234',
      displayName: 'Lena Brandt',
      behaviors: { role: 'member', locale: 'de-DE' },
      seed: { orders: 5, addresses: 2 },
    },
    {
      id: 'prof-avery',
      email: 'avery@kotes.test',
      password: 'demo1234',
      displayName: 'Avery Kote',
      behaviors: { role: 'admin', locale: 'en-US' },
    },
    {
      id: 'prof-jordan',
      email: 'jordan@kotes.test',
      password: 'demo1234',
      displayName: 'Jordan Vale',
      behaviors: { role: 'member', locked: true },
    },
    {
      id: 'prof-noor',
      email: 'noor@kotes.test',
      password: 'demo1234',
      displayName: 'Noor Haddad',
      behaviors: { role: 'member', highErrorRate: 0.5 },
      seed: { orders: 2, addresses: 1 },
    },
    {
      id: 'prof-marc',
      email: 'marc@kotes.test',
      password: 'demo1234',
      displayName: 'Marc Dubois',
      behaviors: { role: 'member', locale: 'fr-FR' },
      seed: { orders: 4, addresses: 1 },
    },
    {
      id: 'prof-priya',
      email: 'priya@kotes.test',
      password: 'demo1234',
      displayName: 'Priya Raman',
      behaviors: { role: 'member', stepUpReauth: true },
      seed: { orders: 2, addresses: 1 },
    },
    {
      id: 'prof-tomas',
      email: 'tomas@kotes.test',
      password: 'demo1234',
      displayName: 'Tomas Vidal',
      behaviors: { role: 'member', sessionExpiresAfter: 8 },
      seed: { orders: 12, addresses: 1 },
    },
    {
      id: 'prof-kai',
      email: 'kai@kotes.test',
      password: 'demo1234',
      displayName: 'Kai Ito',
      behaviors: { role: 'member' },
    },
  ],

  seed: {
    categories: [
      { id: 'cat-home', name: 'Home', slug: 'home' },
      { id: 'cat-kitchen', name: 'Kitchen', slug: 'kitchen' },
      { id: 'cat-outdoors', name: 'Outdoors', slug: 'outdoors' },
      { id: 'cat-desk', name: 'Desk', slug: 'desk' },
    ],

    shipping: { freeThresholdCents: 5000, flatCents: 600 },
    taxRate: 0.08,

    coupons: [
      { code: 'WELCOME10', percentOff: 10 },
      { code: 'HOME15', percentOff: 15, minSubtotalCents: 7500 },
      { code: 'TENOFF', amountOffCents: 1000, minSubtotalCents: 4000 },
    ],

    products: [
      {
        id: 'p-aera-mug',
        slug: 'aera-ceramic-mug',
        name: 'Aera Ceramic Mug',
        category: 'kitchen',
        priceCents: 1800,
        stock: 42,
        rating: 4.6,
        badge: 'bestseller',
        blurb: 'A hefty 12oz mug with a satin glaze.',
        description:
          'Thrown from stoneware and dipped in a soft satin glaze, the Aera mug holds 12oz and keeps its warmth. Dishwasher and microwave safe.',
        tags: ['ceramic', 'drinkware'],
        variants: [{ name: 'Color', options: ['Clay', 'Sage', 'Charcoal'] }],
      },
      {
        id: 'p-loop-throw',
        slug: 'loop-cotton-throw',
        name: 'Loop Cotton Throw',
        category: 'home',
        priceCents: 6400,
        compareAtCents: 8000,
        stock: 12,
        rating: 4.8,
        badge: 'sale',
        blurb: 'Chunky waffle-weave throw in organic cotton.',
        description:
          'A generously sized 50×60" throw in a chunky waffle weave. Made from 100% organic cotton that softens with every wash.',
        tags: ['textiles', 'cotton'],
        variants: [{ name: 'Color', options: ['Oat', 'Rust', 'Indigo'] }],
      },
      {
        id: 'p-pebble-lamp',
        slug: 'pebble-desk-lamp',
        name: 'Pebble Desk Lamp',
        category: 'desk',
        priceCents: 4900,
        stock: 0,
        rating: 4.4,
        blurb: 'Warm, dimmable LED with a smooth river-stone base.',
        description:
          'A soft, dimmable LED lamp with a weighty ceramic base shaped like a river stone. Touch-controlled with three brightness levels.',
        tags: ['lighting'],
      },
      {
        id: 'p-trail-bottle',
        slug: 'trail-insulated-bottle',
        name: 'Trail Insulated Bottle',
        category: 'outdoors',
        priceCents: 3200,
        stock: 88,
        rating: 4.7,
        badge: 'bestseller',
        blurb: 'Double-walled steel; cold for 24h, hot for 12h.',
        description:
          'Vacuum-insulated 18/8 stainless steel that keeps drinks cold for 24 hours or hot for 12. Powder-coated, leakproof, and built for the trail.',
        tags: ['steel', 'drinkware'],
        variants: [
          { name: 'Size', options: ['500ml', '750ml'] },
          { name: 'Color', options: ['Coral', 'Pine', 'Slate'] },
        ],
      },
      {
        id: 'p-nest-basket',
        slug: 'nest-storage-basket',
        name: 'Nest Storage Basket',
        category: 'home',
        priceCents: 2600,
        stock: 30,
        rating: 4.3,
        blurb: 'Handwoven seagrass basket with cotton handles.',
        description:
          'Handwoven from natural seagrass with soft cotton rope handles. Holds blankets, toys, or firewood and folds flat when empty.',
        tags: ['storage'],
      },
      {
        id: 'p-crumb-board',
        slug: 'crumb-cutting-board',
        name: 'Crumb Cutting Board',
        category: 'kitchen',
        priceCents: 3800,
        stock: 17,
        rating: 4.5,
        blurb: 'End-grain acacia board with a juice groove.',
        description:
          'A thick end-grain acacia board that is kind to knife edges, with a perimeter juice groove and routed handholds.',
        tags: ['wood', 'prep'],
      },
      {
        id: 'p-drift-apron',
        slug: 'drift-linen-apron',
        name: 'Drift Linen Apron',
        category: 'kitchen',
        priceCents: 2900,
        compareAtCents: 3600,
        stock: 24,
        rating: 4.2,
        badge: 'sale',
        blurb: 'Stonewashed linen with an adjustable neck strap.',
        description:
          'Cut from stonewashed European linen with a crossback-friendly neck strap, a roomy front pocket, and extra-long ties.',
        tags: ['linen', 'apparel'],
        variants: [{ name: 'Color', options: ['Natural', 'Charcoal'] }],
      },
      {
        id: 'p-summit-socks',
        slug: 'summit-wool-socks',
        name: 'Summit Wool Socks',
        category: 'outdoors',
        priceCents: 1600,
        stock: 120,
        rating: 4.9,
        blurb: 'Cushioned merino socks for long days out.',
        description:
          'Mid-weight merino wool with a cushioned footbed and arch support. Naturally temperature-regulating and odor-resistant.',
        tags: ['merino', 'apparel'],
        variants: [{ name: 'Size', options: ['S', 'M', 'L'] }],
      },
      {
        id: 'p-glow-candle',
        slug: 'glow-soy-candle',
        name: 'Glow Soy Candle',
        category: 'home',
        priceCents: 2200,
        stock: 64,
        rating: 4.6,
        blurb: 'Hand-poured soy wax, ~50 hour burn.',
        description:
          'A clean-burning soy wax candle hand-poured into a reusable tumbler, with a cotton wick and roughly a 50 hour burn time.',
        tags: ['home-fragrance'],
        variants: [{ name: 'Scent', options: ['Cedar', 'Citrus', 'Vanilla'] }],
      },
      {
        id: 'p-forge-pan',
        slug: 'forge-cast-pan',
        name: 'Forge Cast Pan',
        category: 'kitchen',
        priceCents: 7400,
        stock: 9,
        rating: 4.8,
        blurb: 'Pre-seasoned 10" cast iron skillet.',
        description:
          'A pre-seasoned 10" cast iron skillet with a helper handle and pour spouts. Oven-safe to 500°F and built to outlive you.',
        tags: ['cast-iron', 'cookware'],
      },
      {
        id: 'p-camp-plates',
        slug: 'camp-enamel-plate-set',
        name: 'Camp Enamel Plate Set',
        category: 'outdoors',
        priceCents: 4200,
        stock: 21,
        rating: 4.1,
        blurb: 'Set of four chip-resistant enamel plates.',
        description:
          'Four lightweight steel plates finished in speckled enamel with a rolled rim. Stackable, chip-resistant, and campfire-friendly.',
        tags: ['enamel', 'tableware'],
      },
      {
        id: 'p-quill-notebook',
        slug: 'quill-notebook',
        name: 'Quill Notebook',
        category: 'desk',
        priceCents: 1400,
        stock: 200,
        rating: 4.5,
        blurb: 'Lay-flat dot-grid notebook, 180 pages.',
        description:
          'A lay-flat sewn-bound notebook with 180 pages of 100gsm dot-grid paper, a ribbon marker, and a back pocket.',
        tags: ['stationery'],
        variants: [{ name: 'Color', options: ['Kraft', 'Black'] }],
      },
      {
        id: 'p-arc-stand',
        slug: 'arc-monitor-stand',
        name: 'Arc Monitor Stand',
        category: 'desk',
        priceCents: 5600,
        stock: 6,
        rating: 4.4,
        blurb: 'Solid oak riser with a cable channel.',
        description:
          'A solid white-oak monitor riser that lifts your screen to eye level, with a hidden cable channel and a felt-lined base.',
        tags: ['oak', 'desk-setup'],
      },
      {
        id: 'p-halo-cushion',
        slug: 'halo-floor-cushion',
        name: 'Halo Floor Cushion',
        category: 'home',
        priceCents: 5200,
        stock: 15,
        rating: 4.3,
        blurb: 'Oversized tufted cushion with a canvas cover.',
        description:
          'An oversized 26" floor cushion with a tufted, removable canvas cover and a firm recycled-fiber fill. Carry handle included.',
        tags: ['textiles', 'seating'],
        variants: [{ name: 'Color', options: ['Moss', 'Sand', 'Wine'] }],
      },
      {
        id: 'p-tide-towel',
        slug: 'tide-bath-towel',
        name: 'Tide Bath Towel',
        category: 'home',
        priceCents: 2400,
        compareAtCents: 3000,
        stock: 40,
        rating: 4.7,
        badge: 'sale',
        blurb: 'Quick-dry Turkish cotton bath towel.',
        description:
          'A lightweight, quick-drying Turkish cotton bath towel that gets more absorbent with every wash. Generous 30×58" size.',
        tags: ['cotton', 'bath'],
        variants: [{ name: 'Color', options: ['White', 'Sky', 'Sand'] }],
      },
      {
        id: 'p-bloom-can',
        slug: 'bloom-watering-can',
        name: 'Bloom Watering Can',
        category: 'outdoors',
        priceCents: 3400,
        stock: 28,
        rating: 4.2,
        badge: 'new',
        blurb: 'Balanced 1.5L can with a removable rose.',
        description:
          'A powder-coated steel watering can with a long balanced spout and a removable brass rose for a gentle shower. Holds 1.5 liters.',
        tags: ['garden'],
      },
      {
        id: 'p-everyday-towels',
        slug: 'everyday-waffle-kitchen-towels',
        name: 'Everyday Ultra-Soft Waffle-Knit Kitchen Towels — Set of Three, Oat Stripe',
        category: 'kitchen',
        priceCents: 2100,
        stock: 34,
        rating: 4.4,
        blurb: 'Three thirsty towels in stonewashed cotton.',
        description:
          'A set of three generously sized waffle-knit kitchen towels in stonewashed cotton with a woven oat stripe. They shed lint less, dry faster, and soften with every wash.',
        tags: ['cotton', 'prep'],
      },
    ],
  },
};
